@startuml activity_diagram_DECISION
title ⚙️ Activity Diagram - Decision Engine

skinparam backgroundColor #FDFEFE
skinparam activity {
  BackgroundColor #000080
  BorderColor #000060
  FontColor white
  DiamondBackgroundColor #0086b3
  DiamondBorderColor #004466
  StartColor #C0392B
  EndColor #C0392B
}

start

:Ricezione richiesta di diagnosi;
note right
La richiesta contiene i sintomi del paziente
e l’identificativo dell’utente autenticato.
end note

:Richiedi al servizio Aggregator i dati del paziente;
  if (Aggregator disponibile?) then (Sì)
    :Ricevi contesto clinico\n(età, sesso, storico report);
  else (No)
    :Genera errore;
    stop
  endif


:Combina i dati ricevuti con i sintomi correnti;
:Avvia il RAG;

if (Risposta prodotta?) then (Sì)
  :Valida e struttura la risposta\n(decisione, motivazione);
  
else (No)
  :Crea risposta di errore\n(decisione N/A);
endif

:Invia report al Report Management Service;
:Restituisce esito diagnostico;

stop
@enduml