@startuml activity_diagram_AGGREGATOR
title Activity Diagram - Aggregator Service

skinparam backgroundColor #FDFEFE
skinparam activity {
  BackgroundColor #000080
  BorderColor #000060
  FontColor white
  DiamondBackgroundColor #0086b3
  DiamondBorderColor #004466
  StartColor #C0392B
  EndColor #C0392B
}

start

:Ricezione richiesta di aggregazione;

fork
    :Recupera i dati anagrafici dal servizio Auth;
fork again
    :Recupera lo storico dei report dal servizio Report;
end fork

if (Entrambi i servizi rispondono correttamente?) then (Sì)
  :Combina le informazioni anagrafiche con lo storico clinico;
  :Restituisce il contesto aggregato ai servizi richiedenti;
else (No)
  :Genera messaggio di errore "Dati non disponibili";
endif

stop

@enduml